### ISSUE TITLE
FoundError

### ISSUE THREAD

**Issue by Egida** [Its-Vichy/Mirkat#2]
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.6).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
setup.sh: 2: yum: not found
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.22.0)
Requirement already satisfied: paramiko in /usr/local/lib/python3.8/dist-packages (2.7.2)
Requirement already satisfied: cryptography>=2.5 in /usr/lib/python3/dist-packages (from paramiko) (2.8)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.8/dist-packages (from paramiko) (3.2.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib/python3/dist-packages (from paramiko) (1.3.0)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt>=3.1.3->paramiko) (1.14.6)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3/dist-packages (from bcrypt>=3.1.3->paramiko) (1.14.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko) (2.20)
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    setup()
  File "setup.py", line 6, in setup
    base64_payload = f'(echo \'{base64.b64encode(payload)}\' | base64 --decode) | sh'
  File "/usr/lib/python3.8/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "Loader.py", line 55, in <module>
    with open('./Bin/infect.sh', 'r+') as pf:
FileNotFoundError: [Errno 2] No such file or directory: './Bin/infect.sh'
```
How to fix it?

**Comment by Its-Vichy** [comment]
Run the setup and check if infect.sh and mirkat folder was created

**Comment by Egida** [comment]
> Run the setup and check if infect.sh and mirkat folder was created
This is after running setup.py
infect.sh and mirkat folder not created

**Comment by mike2505** [comment]
how you fixed that?
